using Survey.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Survey.Utils
{
    public static class StaticVal
    {
        public static string _strProgressMain = string.Empty;
        public static List<SymbolCustom> _lSymbol = new List<SymbolCustom>
        {
            new SymbolCustom { Priority = 1, Symbol = "vanryusdt",HieuSuat = 187.81},
            new SymbolCustom { Priority = 2, Symbol = "pepeusdt",HieuSuat = 182.18},
            new SymbolCustom { Priority = 3, Symbol = "ftmusdt",HieuSuat = 139.75},
            new SymbolCustom { Priority = 4, Symbol = "tiausdt",HieuSuat = 137.4},
            new SymbolCustom { Priority = 5, Symbol = "chzusdt",HieuSuat = 111.75},
            new SymbolCustom { Priority = 6, Symbol = "lendusdt",HieuSuat = 107.96},
            new SymbolCustom { Priority = 7, Symbol = "ankrusdt",HieuSuat = 103.54},
            new SymbolCustom { Priority = 8, Symbol = "alphausdt",HieuSuat = 104.87},
            new SymbolCustom { Priority = 9, Symbol = "xvsusdt",HieuSuat = 88.17},
            new SymbolCustom { Priority = 10, Symbol = "tfuelusdt",HieuSuat = 81.45},
            new SymbolCustom { Priority = 11, Symbol = "lunausdt",HieuSuat = 81.13},
            new SymbolCustom { Priority = 12, Symbol = "bonkusdt",HieuSuat = 79.18},
            new SymbolCustom { Priority = 13, Symbol = "nknusdt",HieuSuat = 76.95},
            new SymbolCustom { Priority = 14, Symbol = "btcstusdt",HieuSuat = 76.63},
            new SymbolCustom { Priority = 15, Symbol = "dentusdt",HieuSuat = 67.27},
            new SymbolCustom { Priority = 16, Symbol = "avaxusdt",HieuSuat = 66.62},
            new SymbolCustom { Priority = 17, Symbol = "maticusdt",HieuSuat = 59.17},
            new SymbolCustom { Priority = 18, Symbol = "egldusdt",HieuSuat = 57.13},
            new SymbolCustom { Priority = 19, Symbol = "gmtusdt",HieuSuat = 56.77},
            new SymbolCustom { Priority = 20, Symbol = "bttusdt",HieuSuat = 56.77},
            new SymbolCustom { Priority = 21, Symbol = "vthousdt",HieuSuat = 53.93},
            new SymbolCustom { Priority = 22, Symbol = "ntrnusdt",HieuSuat = 52.63},
            new SymbolCustom { Priority = 23, Symbol = "seiusdt",HieuSuat = 51.05},
            new SymbolCustom { Priority = 24, Symbol = "santosusdt",HieuSuat = 47.58},
            new SymbolCustom { Priority = 25, Symbol = "galausdt",HieuSuat = 47.01},
            new SymbolCustom { Priority = 26, Symbol = "aptusdt",HieuSuat = 47},
            new SymbolCustom { Priority = 27, Symbol = "fetusdt",HieuSuat = 46.43},
            new SymbolCustom { Priority = 28, Symbol = "bandusdt",HieuSuat = 46.01},
            new SymbolCustom { Priority = 29, Symbol = "bntusdt",HieuSuat = 44.72},
            new SymbolCustom { Priority = 30, Symbol = "arusdt",HieuSuat = 44.31},
            new SymbolCustom { Priority = 31, Symbol = "solusdt",HieuSuat = 44.16},
            new SymbolCustom { Priority = 32, Symbol = "pendleusdt",HieuSuat = 43.76},
            new SymbolCustom { Priority = 33, Symbol = "npxsusdt",HieuSuat = 42.7},
            new SymbolCustom { Priority = 34, Symbol = "wldusdt",HieuSuat = 41.67},
            new SymbolCustom { Priority = 35, Symbol = "winusdt",HieuSuat = 41.23},
            new SymbolCustom { Priority = 36, Symbol = "opusdt",HieuSuat = 40.52},
            new SymbolCustom { Priority = 37, Symbol = "mithusdt",HieuSuat = 40.17},
            new SymbolCustom { Priority = 38, Symbol = "thetausdt",HieuSuat = 39.58},
            new SymbolCustom { Priority = 39, Symbol = "nearusdt",HieuSuat = 39.48},
            //new SymbolCustom { Priority = 40, Symbol = "oneusdt",HieuSuat = 38},
            //new SymbolCustom { Priority = 41, Symbol = "osmousdt",HieuSuat = 37.72},
            //new SymbolCustom { Priority = 42, Symbol = "bzrxusdt",HieuSuat = 37.43},
            //new SymbolCustom { Priority = 43, Symbol = "injusdt",HieuSuat = 37.34},
            //new SymbolCustom { Priority = 44, Symbol = "auctionusdt",HieuSuat = 37.05},
            //new SymbolCustom { Priority = 45, Symbol = "funusdt",HieuSuat = 35.08},
            //new SymbolCustom { Priority = 46, Symbol = "hbarusdt",HieuSuat = 34.55},
            //new SymbolCustom { Priority = 47, Symbol = "wrxusdt",HieuSuat = 33.71},
            //new SymbolCustom { Priority = 48, Symbol = "filusdt",HieuSuat = 33.38},
            //new SymbolCustom { Priority = 49, Symbol = "bchabcusdt",HieuSuat = 33.01},
            //new SymbolCustom { Priority = 50, Symbol = "rvnusdt",HieuSuat = 32.83},
            //new SymbolCustom { Priority = 51, Symbol = "srmusdt",HieuSuat = 32.43},
            //new SymbolCustom { Priority = 52, Symbol = "uniusdt",HieuSuat = 32.36},
            //new SymbolCustom { Priority = 53, Symbol = "bnbusdt",HieuSuat = 32.31},
            //new SymbolCustom { Priority = 54, Symbol = "grtusdt",HieuSuat = 31.18},
            //new SymbolCustom { Priority = 55, Symbol = "rayusdt",HieuSuat = 31.18},
            //new SymbolCustom { Priority = 56, Symbol = "viteusdt",HieuSuat = 30.96},
            //new SymbolCustom { Priority = 57, Symbol = "fttusdt",HieuSuat = 30.58},
            //new SymbolCustom { Priority = 58, Symbol = "altusdt",HieuSuat = 29.83},


            //new SymbolCustom { Priority = 59, Symbol = "sandusdt",HieuSuat = 28.97},
            //new SymbolCustom { Priority = 60, Symbol = "manausdt",HieuSuat = 28.74},
            //new SymbolCustom { Priority = 61, Symbol = "ckbusdt",HieuSuat = 27.72},
            //new SymbolCustom { Priority = 62, Symbol = "iotxusdt",HieuSuat = 27.1},
            //new SymbolCustom { Priority = 63, Symbol = "idusdt",HieuSuat = 26.74},
            //new SymbolCustom { Priority = 64, Symbol = "perlusdt",HieuSuat = 25.79},
            //new SymbolCustom { Priority = 65, Symbol = "btgusdt",HieuSuat = 25.13},
            //new SymbolCustom { Priority = 66, Symbol = "runeusdt",HieuSuat = 24.78},
            //new SymbolCustom { Priority = 67, Symbol = "tctusdt",HieuSuat = 24.78},
            //new SymbolCustom { Priority = 68, Symbol = "ernusdt",HieuSuat = 24.69},
            //new SymbolCustom { Priority = 69, Symbol = "ampusdt",HieuSuat = 24.67},
            //new SymbolCustom { Priority = 70, Symbol = "hotusdt",HieuSuat = 24.22},
            //new SymbolCustom { Priority = 71, Symbol = "zilusdt",HieuSuat = 23.96},
            //new SymbolCustom { Priority = 72, Symbol = "linkusdt",HieuSuat = 23.64},
            //new SymbolCustom { Priority = 73, Symbol = "ilvusdt",HieuSuat = 23.49},
            //new SymbolCustom { Priority = 74, Symbol = "jasmyusdt",HieuSuat = 23.43},
            //new SymbolCustom { Priority = 75, Symbol = "crvusdt",HieuSuat = 23.27},
            //new SymbolCustom { Priority = 76, Symbol = "astrusdt",HieuSuat = 22.75},
            //new SymbolCustom { Priority = 77, Symbol = "axsusdt",HieuSuat = 22.71},
            //new SymbolCustom { Priority = 78, Symbol = "lrcusdt",HieuSuat = 22.34},
            //new SymbolCustom { Priority = 79, Symbol = "zenusdt",HieuSuat = 22},
            //new SymbolCustom { Priority = 80, Symbol = "twtusdt",HieuSuat = 21.69},
            //new SymbolCustom { Priority = 81, Symbol = "bttcusdt",HieuSuat = 21.61},
            //new SymbolCustom { Priority = 82, Symbol = "aiusdt",HieuSuat = 21.31},
            //new SymbolCustom { Priority = 83, Symbol = "storjusdt",HieuSuat = 21.26},
            //new SymbolCustom { Priority = 84, Symbol = "vetusdt",HieuSuat = 21.07},
            //new SymbolCustom { Priority = 85, Symbol = "stgusdt",HieuSuat = 21.05},
            //new SymbolCustom { Priority = 86, Symbol = "fxsusdt",HieuSuat = 20.94},
            //new SymbolCustom { Priority = 87, Symbol = "etcusdt",HieuSuat = 20.81},
            //new SymbolCustom { Priority = 88, Symbol = "renusdt",HieuSuat = 20.73},
            //new SymbolCustom { Priority = 89, Symbol = "wnxmusdt",HieuSuat = 20.67},
            //new SymbolCustom { Priority = 90, Symbol = "neousdt",HieuSuat = 20.39},
            //new SymbolCustom { Priority = 91, Symbol = "truusdt",HieuSuat = 20.16},
            //new SymbolCustom { Priority = 92, Symbol = "movrusdt",HieuSuat = 20.12},
            //new SymbolCustom { Priority = 93, Symbol = "hntusdt",HieuSuat = 19.87},
            //new SymbolCustom { Priority = 94, Symbol = "frontusdt",HieuSuat = 19.76},
            //new SymbolCustom { Priority = 95, Symbol = "hifiusdt",HieuSuat = 19.4},
            //new SymbolCustom { Priority = 96, Symbol = "minausdt",HieuSuat = 19.05},
            //new SymbolCustom { Priority = 97, Symbol = "klayusdt",HieuSuat = 18.92},
            //new SymbolCustom { Priority = 98, Symbol = "mtlusdt",HieuSuat = 18.9},
            //new SymbolCustom { Priority = 99, Symbol = "leverusdt",HieuSuat = 18.88},
            //new SymbolCustom { Priority = 100, Symbol = "keyusdt",HieuSuat = 18.59},
            //new SymbolCustom { Priority = 101, Symbol = "qiusdt",HieuSuat = 17.99},
            //new SymbolCustom { Priority = 102, Symbol = "firousdt",HieuSuat = 17.78},
            //new SymbolCustom { Priority = 103, Symbol = "memeusdt",HieuSuat = 17.7},
            //new SymbolCustom { Priority = 104, Symbol = "ogusdt",HieuSuat = 17.61},
            //new SymbolCustom { Priority = 105, Symbol = "ancusdt",HieuSuat = 17.58},
            //new SymbolCustom { Priority = 106, Symbol = "ksmusdt",HieuSuat = 17.46},
            //new SymbolCustom { Priority = 107, Symbol = "ornusdt",HieuSuat = 17.46},
            //new SymbolCustom { Priority = 108, Symbol = "troyusdt",HieuSuat = 17.45},
            //new SymbolCustom { Priority = 109, Symbol = "stmxusdt",HieuSuat = 17.42},
            //new SymbolCustom { Priority = 110, Symbol = "btcusdt",HieuSuat = 17.24},
            //new SymbolCustom { Priority = 111, Symbol = "omgusdt",HieuSuat = 17.06},
            //new SymbolCustom { Priority = 112, Symbol = "trbusdt",HieuSuat = 17.06},
            //new SymbolCustom { Priority = 113, Symbol = "datausdt",HieuSuat = 17.03},
            //new SymbolCustom { Priority = 114, Symbol = "unfiusdt",HieuSuat = 16.68},
            //new SymbolCustom { Priority = 115, Symbol = "mdtusdt",HieuSuat = 16.63},
            //new SymbolCustom { Priority = 116, Symbol = "gnousdt",HieuSuat = 16.45},
            //new SymbolCustom { Priority = 117, Symbol = "omusdt",HieuSuat = 16.26},
            //new SymbolCustom { Priority = 118, Symbol = "cotiusdt",HieuSuat = 16.08},
            //new SymbolCustom { Priority = 119, Symbol = "arpausdt",HieuSuat = 15.9},
            //new SymbolCustom { Priority = 120, Symbol = "audiousdt",HieuSuat = 15.77},
            //new SymbolCustom { Priority = 121, Symbol = "dockusdt",HieuSuat = 15.72},
            //new SymbolCustom { Priority = 122, Symbol = "dotusdt",HieuSuat = 15.7},
            //new SymbolCustom { Priority = 123, Symbol = "api3usdt",HieuSuat = 15.6},
            //new SymbolCustom { Priority = 124, Symbol = "psgusdt",HieuSuat = 15.49},
            //new SymbolCustom { Priority = 125, Symbol = "xvgusdt",HieuSuat = 15.35},
            //new SymbolCustom { Priority = 126, Symbol = "duskusdt",HieuSuat = 14.96},
            //new SymbolCustom { Priority = 127, Symbol = "ssvusdt",HieuSuat = 14.84},
            //new SymbolCustom { Priority = 128, Symbol = "scusdt",HieuSuat = 14.76},
            //new SymbolCustom { Priority = 129, Symbol = "aceusdt",HieuSuat = 14.67},
            //new SymbolCustom { Priority = 130, Symbol = "adausdt",HieuSuat = 14.62},
            //new SymbolCustom { Priority = 131, Symbol = "portousdt",HieuSuat = 14.58},
            //new SymbolCustom { Priority = 132, Symbol = "anyusdt",HieuSuat = 14.55},
            //new SymbolCustom { Priority = 133, Symbol = "dgbusdt",HieuSuat = 14.52},
            //new SymbolCustom { Priority = 134, Symbol = "qtumusdt",HieuSuat = 14.42},
            //new SymbolCustom { Priority = 135, Symbol = "sxpusdt",HieuSuat = 14.4},
            //new SymbolCustom { Priority = 136, Symbol = "wbethusdt",HieuSuat = 14.39},
            //new SymbolCustom { Priority = 137, Symbol = "mftusdt",HieuSuat = 14.36},
            //new SymbolCustom { Priority = 138, Symbol = "slpusdt",HieuSuat = 14.2},
            //new SymbolCustom { Priority = 139, Symbol = "wavesusdt",HieuSuat = 13.97},
            //new SymbolCustom { Priority = 140, Symbol = "nbsusdt",HieuSuat = 13.94},
            //new SymbolCustom { Priority = 141, Symbol = "highusdt",HieuSuat = 13.74},
            //new SymbolCustom { Priority = 142, Symbol = "kavausdt",HieuSuat = 13.6},
            //new SymbolCustom { Priority = 143, Symbol = "tribeusdt",HieuSuat = 13.59},
            //new SymbolCustom { Priority = 144, Symbol = "1inchusdt",HieuSuat = 13.34},
            //new SymbolCustom { Priority = 145, Symbol = "atausdt",HieuSuat = 13.18},
            //new SymbolCustom { Priority = 146, Symbol = "ethusdt",HieuSuat = 13.04},
            //new SymbolCustom { Priority = 147, Symbol = "bnxusdt",HieuSuat = 12.96},
            //new SymbolCustom { Priority = 148, Symbol = "ctsiusdt",HieuSuat = 12.9},
            //new SymbolCustom { Priority = 149, Symbol = "gftusdt",HieuSuat = 12.77},
            //new SymbolCustom { Priority = 150, Symbol = "suiusdt",HieuSuat = 12.77},
            //new SymbolCustom { Priority = 150, Symbol = "cakeusdt",HieuSuat = 12.75},
            //new SymbolCustom { Priority = 150, Symbol = "fluxusdt",HieuSuat = 12.66},
            //new SymbolCustom { Priority = 150, Symbol = "jstusdt",HieuSuat = 12.58},
            //new SymbolCustom { Priority = 150, Symbol = "spellusdt",HieuSuat = 12.51},
            //new SymbolCustom { Priority = 150, Symbol = "dashusdt",HieuSuat = 12.49},
            //new SymbolCustom { Priority = 150, Symbol = "blzusdt",HieuSuat = 12.04},
            //new SymbolCustom { Priority = 150, Symbol = "straxusdt",HieuSuat = 11.97},
            //new SymbolCustom { Priority = 150, Symbol = "dcrusdt",HieuSuat = 11.95},
            //new SymbolCustom { Priority = 150, Symbol = "bswusdt",HieuSuat = 11.89},
            //new SymbolCustom { Priority = 150, Symbol = "cvxusdt",HieuSuat = 11.84},
            //new SymbolCustom { Priority = 150, Symbol = "avausdt",HieuSuat = 11.77},
            //new SymbolCustom { Priority = 150, Symbol = "belusdt",HieuSuat = 11.5},
            //new SymbolCustom { Priority = 150, Symbol = "xtzusdt",HieuSuat = 11.47},
            //new SymbolCustom { Priority = 150, Symbol = "mkrusdt",HieuSuat = 11.32},
            //new SymbolCustom { Priority = 150, Symbol = "wingusdt",HieuSuat = 11.11},
            //new SymbolCustom { Priority = 150, Symbol = "dogeusdt",HieuSuat = 10.99},
            //new SymbolCustom { Priority = 150, Symbol = "xrpusdt",HieuSuat = 10.87},
            //new SymbolCustom { Priority = 150, Symbol = "ognusdt",HieuSuat = 10.85},
            //new SymbolCustom { Priority = 150, Symbol = "zecusdt",HieuSuat = 10.46},
            //new SymbolCustom { Priority = 150, Symbol = "xlmusdt",HieuSuat = 9.76},
            //new SymbolCustom { Priority = 150, Symbol = "chrusdt",HieuSuat = 9.73},
        };
    }
}
